syntax on

set so=7
set nu
:set expandtab
:set tabstop=2

"vim plugins
call plug#begin('~/.vim/plugged')
Plug 'elzr/vim-json'
Plug 'jonathanfilip/vim-lucius'
call plug#end()

"Colors
colorscheme lucius
LuciusWhite
set t_Co=256

