# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
bindkey '^R' history-incremental-search-backward
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/Users/stephan.bauer/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

#gitradar
setopt PROMPT_SUBST
export PROMPT="[38;05;4m%~[00m\$(git-radar --zsh --fetch)[38;05;4m>[00m "

# alias
alias ll='ls -GFhla'
alias ag='ag --smart-case --color-line-number "1;34"'
alias beer='brew -v update; brew upgrade --force-bottle --cleanup; brew cleanup; brew prune; brew doctor'
alias huff='cd ../sherlock; git uff; cd ../watson; git uff; cd ../hudson; git uff'
alias mt='mvn clean test -Dstyle.color=always'

# colorize terminal
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
export TERM=screen-256color

function sethostname() {
  export HOSTNAME=$(ip a | grep -Eo "inet (addr:)?([0-9]*\\.){3}[0-9]*" | grep -Eo "([0-9]*\\.){3}[0-9]*" | grep -v "127.0.0.1" | grep -v "172.")
  echo "set \e[34;1mHOSTNAME=\e[34;4m$HOSTNAME\e[0m for sbt to docker communication"
}

function compose () {
  sethostname
  # to gain access to docker registry
  source ../aws-bootstrap/.venv/bin/activate
  eval $(aws ecr get-login --region eu-west-1 | sed 's/-e none//')
  # to ensure up to date docker images with fixture data
  docker-compose kill
  docker-compose rm -f
  docker-compose pull
  # to start docker containers
  docker-compose up -d
}

function compose-kill-all {
  for i in $(docker ps | tail -n +2 | cut -d" " -f1); do docker kill $i; done
}

export JAVA_HOME=$(/usr/libexec/java_home)
export PATH=$PATH:/home/sbauer/.cargo/bin
export PATH=$PATH:/usr/local/go/bin
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:/home/sbauer/lib/goat
export PATH="/Users/stephan.bauer/workspace/mdht:$PATH"
export AD_USERNAME=stephan.bauer

#eval $(docker-machine env default)

alias ssh-staging-eu-settings-backend='ssh -o IdentitiesOnly=yes -i ~/secrets/keys/mjolnir-staging-eu-us.pem cloud-user@10.225.161.206'
alias ssh-playground-eu-settings-backend='ssh -o IdentitiesOnly=yes -i ~/secrets/keys/mjolnir-production-eu.pem cloud-user@10.228.176.247'
alias ssh-production-eu-settings-backend='ssh -o IdentitiesOnly=yes -i ~/secrets/keys/mjolnir-production-eu.pem cloud-user@10.228.177.88'
alias ssh-staging-eu-moma='ssh -o IdentitiesOnly=yes -i ~/secrets/keys/mjolnir-staging-eu-us.pem cloud-user@10.225.153.166'
alias ssh-staging-us-moma='ssh -o IdentitiesOnly=yes -i ~/secrets/keys/mjolnir-staging-eu-us.pem cloud-user@10.225.156.242'
alias ssh-playground-eu-moma='ssh -o IdentitiesOnly=yes -i ~/secrets/keys/mjolnir-production-eu.pem cloud-user@10.228.175.178'
alias ssh-playground-us-moma='ssh -o IdentitiesOnly=yes -i ~/secrets/keys/mjolnir-production-us.pem cloud-user@10.226.246.54'
alias ssh-production-eu-moma='ssh -o IdentitiesOnly=yes -i ~/secrets/keys/mjolnir-production-eu.pem cloud-user@10.228.169.136'
alias ssh-production-us-moma='ssh -o IdentitiesOnly=yes -i ~/secrets/keys/mjolnir-production-us.pem cloud-user@10.226.244.213'
alias ssh-production-eu-tamer='ssh -o IdentitiesOnly=yes -i ~/secrets/keys/mjolnir-production-eu.pem cloud-user@10.228.169.175'
alias ssh-playground-eu-tamer='ssh -o IdentitiesOnly=yes -i ~/secrets/keys/mjolnir-production-eu.pem cloud-user@10.228.169.249'
alias ssh-production-us-tamer='ssh -o IdentitiesOnly=yes -i ~/secrets/keys/mjolnir-production-us.pem cloud-user@10.226.245.2'
alias ssh-staging-eu-tamer='ssh -o IdentitiesOnly=yes -i ~/secrets/keys/mjolnir-staging-eu-us.pem cloud-user@10.225.162.62'
alias ssh-playground-eu-moma-testpartner='ssh -o IdentitiesOnly=yes -i ~/secrets/keys/mjolnir-production-eu.pem cloud-user@10.228.173.137'
alias ssh-production-eu-moma-salesforce='ssh -o IdentitiesOnly=yes -i ~/secrets/keys/mjolnir-production-eu.pem cloud-user@10.228.176.28'
alias ssh-production-us-moma-salesforce='ssh -o IdentitiesOnly=yes -i ~/secrets/keys/mjolnir-production-us.pem cloud-user@10.226.246.73'
alias ssh-production-eu-bouncer='ssh -o IdentitiesOnly=yes -i ~/secrets/keys/mjolnir-production-eu.pem cloud-user@10.228.169.227'
alias ssh-playground-eu-bouncer='ssh -o IdentitiesOnly=yes -i ~/secrets/keys/mjolnir-production-eu.pem cloud-user@10.228.173.138'

alias localdocker='docker run -it --rm -p 9999:8080 -v $PWD:/home/wiremock rodolpheche/wiremock --verbose'

