# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/Users/stephan.bauer/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

#gitradar
setopt PROMPT_SUBST
export PROMPT="[38;05;4m%~[00m\$(git-radar --zsh --fetch)[38;05;4m>[00m "

# alias
alias ll='ls -GFhla'
alias ag='ag --smart-case --color-line-number "1;34"'
alias beer='brew -v update; brew upgrade --force-bottle --cleanup; brew cleanup; brew prune; brew doctor'
alias huff='cd ../sherlock; git uff; cd ../watson; git uff; cd ../hudson; git uff'

# colorize terminal
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
export TERM=screen-256color

function sethostname() {
  export HOSTNAME=$(ip a | grep -Eo "inet (addr:)?([0-9]*\\.){3}[0-9]*" | grep -Eo "([0-9]*\\.){3}[0-9]*" | grep -v "127.0.0.1" | grep -v "172.")
  echo "set \e[34;1mHOSTNAME=\e[34;4m$HOSTNAME\e[0m for sbt to docker communication"
}

function compose () {
  sethostname
  # to gain access to docker registry
  source ../aws-bootstrap/.venv/bin/activate
  eval $(aws ecr get-login --region eu-west-1 | sed 's/-e none//')
  # to ensure up to date docker images with fixture data
  docker-compose kill
  docker-compose rm -f
  docker-compose pull
  # to start docker containers
  docker-compose up -d
}

function compose-kill-all {
  for i in $(docker ps | tail -n +2 | cut -d" " -f1); do docker kill $i; done
}

alias fbjenkins="fw ls | fzf | xargs fw inspect -j | jq -r '.git' | cut -d : -f 2 | sed 's/\.git$//g' | sed 's/\(.*\)\/\(.*\)/https:\/\/jenkins.21re.works\/job\/\1\/job\/\2\/job\/master\//g' | xargs xdg-open"

export PATH=$PATH:/home/sbauer/.cargo/bin
export PATH=$PATH:/usr/local/go/bin
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:/home/sbauer/lib/goat

#eval $(docker-machine env default)

